const translations = {
    fr: {
        title: "Instant Weather",
        instantWeather: "Instant Weather",
        postalCodeLabel: "Code Postal :",
        searchButton: "Rechercher",
        selectDateOption: "Sélectionnez une date :",
        selectCityOption: "--Sélectionnez une ville--",
        daysLabel: "Nombre de jours pour les prévisions (1 à 7) :",
        daysValue: "jour",
        additionalInfoLabel: "Informations supplémentaires à afficher :",
        latitudeLabel: "Latitude",
        longitudeLabel: "Longitude",
        rainLabel: "Cumul de pluie sur la journée en mm",
        windSpeedLabel: "Vent moyen à 10 mètres en km/h",
        windDirectionLabel: "Direction du vent en degrés (0 à 360°)",
        showForecastButton: "Afficher les prévisions",
        selectDateOption: "--Sélectionnez une date--",
        refreshButton: "Retour à l'accueil",
        networkError: 'Erreur réseau ou serveur',
        weatherDataError: 'Erreur lors de la récupération des données météo.',
        forecastFor: 'Prévisions pour',
        minTemp: 'Température minimale',
        maxTemp: 'Température maximale',
        rainProb: 'Probabilité de pluie',
        sunHours: 'Heures d\'ensoleillement',
        rain: 'Cumul de pluie',
        avgWind: 'Vent moyen',
        windDirection: 'Direction du vent',
        selectCity: 'Veuillez sélectionner une ville.',
        days: 'jour',
        daysPlural: 'jours',
        fahrenheit: '°F',
        celsius: '°C'
    },
    en: {
        title: "Instant Weather",
        instantWeather: "Instant Weather",
        postalCodeLabel: "Zip Code:",
        searchButton: "Search",
        selectDateOption: "Select a date:",
        selectCityOption: "--Select a city--",
        daysLabel: "Number of days for forecasts (1 to 7):",
        daysValue: "day",
        additionalInfoLabel: "Additional information to display:",
        latitudeLabel: "Latitude",
        longitudeLabel: "Longitude",
        rainLabel: "Rain accumulation during the day in mm",
        windSpeedLabel: "Average wind at 10 meters in km/h",
        windDirectionLabel: "Wind direction in degrees (0 to 360°)",
        showForecastButton: "Show Forecast",
        selectDateOption: "--Select a date--",
        refreshButton: "Back to Home",
        networkError: 'Network or server error',
        weatherDataError: 'Error retrieving weather data.',
        forecastFor: 'Forecast for',
        minTemp: 'Minimum temperature',
        maxTemp: 'Maximum temperature',
        rainProb: 'Probability of rain',
        sunHours: 'Sunshine hours',
        rain: 'Rain accumulation',
        avgWind: 'Average wind',
        windDirection: 'Wind direction',
        selectCity: 'Please select a city.',
        days: 'day',
        daysPlural: 'days',
        fahrenheit: '°F',
        celsius: '°C'
    }
};
